import { test, expect } from '@playwright/test'

test('quiet theme: direct study entry, filter reset, keyboard self-rating and reduced motion', async ({page}) => {
  await page.goto('/')
  await page.screenshot({path:'test-results/design-login.png',fullPage:true})
  await page.getByRole('button',{name:'Нет аккаунта? Зарегистрироваться'}).click()
  await page.getByLabel('Email',{exact:true}).fill(`design-${Date.now()}@example.com`)
  await page.getByLabel('Пароль',{exact:true}).fill('browser-test-pass-42')
  await page.getByRole('button',{name:'Создать аккаунт'}).click()
  await expect(page.getByRole('heading',{name:'Подготовка в своём темпе'})).toBeVisible()
  await page.screenshot({path:'test-results/design-home.png',fullPage:true})
  await page.getByRole('button',{name:'Изучать вопросы'}).click()
  await expect(page.getByRole('button',{name:'Вопросы',exact:true})).toHaveAttribute('aria-current','page')
  await page.getByLabel('Направление',{exact:true}).selectOption('python')
  await page.getByLabel('Поиск',{exact:true}).fill('нет такого вопроса')
  await expect(page.getByRole('heading',{name:'Пока нет опубликованных карточек'})).toBeVisible()
  await page.getByRole('button',{name:'Сбросить фильтры'}).click()
  await expect(page.getByLabel('Направление',{exact:true})).toHaveValue('python')
  await expect(page.getByLabel('Поиск',{exact:true})).toHaveValue('')
  await page.getByRole('button',{name:/Вопрос 1: как работает транзакция/}).click()
  const rating=page.getByRole('button',{name:'Знаю',exact:true})
  await rating.focus()
  await page.keyboard.press('Space')
  await expect(rating).toHaveAttribute('aria-pressed','true')
  await page.getByRole('button',{name:'Сохранить ответ и отметку'}).click()
  await expect(page.getByRole('status').filter({hasText:'Ответ и самооценка сохранены'})).toBeVisible()
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.getByRole('button',{name:'Раскрыть проверенный эталон'}).click()
  await expect(page.locator('.study-reference')).toHaveCSS('animation-name','none')
  await page.screenshot({path:'test-results/design-answer.png',fullPage:true})
  for (const width of [390,768]) {
    await page.setViewportSize({width,height:844})
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
    await page.screenshot({path:`test-results/design-answer-${width}.png`,fullPage:true})
  }
})
