import { test, expect, Page } from '@playwright/test'

async function register(page:Page,email:string) {
  await page.goto('/')
  await page.getByRole('button',{name:'Нет аккаунта? Зарегистрироваться'}).click()
  await page.getByLabel('Email',{exact:true}).fill(email)
  await page.getByLabel('Пароль',{exact:true}).fill('browser-test-pass-42')
  await page.getByRole('button',{name:'Создать аккаунт'}).click()
  await expect(page.getByRole('heading',{name:'Ваш следующий шаг — ближе'})).toBeVisible()
}

test('full journey, microphone denial, session continuation and statistics',async({page})=>{
  const errors:string[]=[]
  page.on('pageerror',e=>errors.push(e.message))
  const email=`journey-${Date.now()}@example.com`
  await register(page,email)
  await page.getByRole('button',{name:/journey-.*Frontend/}).click()
  await page.getByLabel('Направление',{exact:true}).selectOption('python')
  await page.getByRole('button',{name:'Сохранить профиль'}).click()
  await expect(page.getByRole('status').filter({hasText:'Профиль сохранён'})).toBeVisible()
  await page.getByRole('button',{name:'Моё резюме',exact:true}).click()
  await page.getByLabel('Текст резюме',{exact:true}).fill('Разработчик Python. Учебный трекер задач на Python и PostgreSQL. Закончил курс Python.')
  await page.getByRole('button',{name:'Добавить текст'}).click()
  await page.getByRole('button',{name:'Извлечь факты с ИИ'}).click()
  await expect(page.getByLabel('Кратко о себе')).toHaveValue('Разработчик Python')
  await page.getByRole('button',{name:'Подтвердить факты'}).click()
  await expect(page.getByRole('status').filter({hasText:'Профиль резюме подтверждён'})).toBeVisible()
  await page.getByRole('button',{name:'Вакансии',exact:true}).click()
  await expect(page.getByRole('button',{name:'Добавить вакансию',exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'Обновить вакансии',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Python developer',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Оценить соответствие · до 20'}).click()
  await expect(page.getByText('75% соответствие')).toBeVisible()
  await page.getByRole('button',{name:'Подготовить отклик'}).click()
  await page.getByRole('button',{name:'Подготовить черновик'}).click()
  await expect(page.getByLabel('Редактор документа')).toHaveValue(/Python/)
  await page.getByRole('button',{name:'Сохранить',exact:true}).click()
  const downloadPromise=page.waitForEvent('download')
  await page.getByRole('link',{name:'Скачать DOCX'}).click()
  const download=await downloadPromise
  expect(download.suggestedFilename()).toBe('jobfinder-document.docx')
  await page.getByRole('button',{name:'Подготовка',exact:true}).click()
  await page.getByLabel('Вакансия',{exact:true}).selectOption({label:'Python developer · Example team'})
  await page.getByRole('button',{name:'Составить план'}).click()
  await expect(page.getByText('0 / 7 дней')).toBeVisible()
  await page.getByRole('button',{name:'Отметить день 1',exact:true}).click()
  await expect(page.getByText('1 / 7 дней')).toBeVisible()
  await page.getByRole('button',{name:'Интервью',exact:true}).click()
  await page.getByLabel('Вакансия',{exact:true}).selectOption({label:'Python developer · Example team'})
  await page.getByRole('button',{name:'Начать интервью',exact:true}).click()
  await expect(page.getByText('Вопрос 1 из 5')).toBeVisible()
  await page.evaluate(()=>{Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:()=>Promise.reject(new DOMException('Denied','NotAllowedError'))})})
  await page.getByRole('button',{name:'Записать ответ'}).click()
  await expect(page.getByText('Микрофон недоступен.',{exact:false})).toBeVisible()
  for(let i=0;i<5;i++) {
    await page.getByLabel('Ваш ответ',{exact:true}).fill('Транзакция фиксирует изменения целиком. Rollback отменяет все изменения.')
    await page.getByLabel('Я проверил текст ответа').check()
    await page.getByRole('button',{name:'Оценить ответ',exact:true}).click()
    if(i<4) await expect(page.getByText(`Вопрос ${i+2} из 5`)).toBeVisible()
    if(i===0) {
      await page.reload()
      await page.getByRole('button',{name:'Интервью',exact:true}).click()
      await expect(page.getByText('Вопрос 2 из 5')).toBeVisible()
    }
  }
  await expect(page.getByRole('heading',{name:'Интервью завершено'})).toBeVisible()
  await page.getByRole('button',{name:'Мой прогресс',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Динамика оценок'})).toBeVisible()
  await expect(page.getByText('5 ответов',{exact:false})).toBeVisible()
  await page.getByRole('button',{name:'Выйти',exact:true}).click()
  await page.getByLabel('Email',{exact:true}).fill(email)
  await page.getByLabel('Пароль',{exact:true}).fill('browser-test-pass-42')
  await page.getByRole('button',{name:'Войти',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Ваш следующий шаг — ближе'})).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true})
  expect(errors).toEqual([])
})

test('mobile layout and navigation',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await register(page,`mobile-${Date.now()}@example.com`)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true})
  await page.getByRole('button',{name:'Моё резюме',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Добавьте резюме'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})

test('CV sections without AI, provider unavailable and local font',async({page})=>{
  await page.route('**/api/v1/connections', route=>route.fulfill({json:{openai:false,hh:false,hh_last:null}}))
  await register(page,`sections-${Date.now()}@example.com`)
  await page.getByRole('button',{name:'Моё резюме',exact:true}).click()
  await page.getByLabel('Текст резюме',{exact:true}).fill('О себе\nРазработчик Python\nНавыки: Python, SQL\nОпыт работы\nРазработал сервис\nОбразование\nУниверситет\nПроекты\nТрекер задач\nЯзыки: Русский, English B1')
  await page.getByRole('button',{name:'Добавить текст',exact:true}).click()
  await expect(page.getByLabel('Кратко о себе')).toHaveValue('Разработчик Python')
  await expect(page.getByLabel('Навыки',{exact:true})).toHaveValue('Python\nSQL')
  await expect(page.getByLabel('Опыт работы',{exact:true})).toHaveValue('Разработал сервис')
  await expect(page.getByRole('button',{name:'Извлечь факты с ИИ'})).toBeDisabled()
  await page.evaluate(()=>document.fonts.ready)
  expect(await page.evaluate(()=>document.fonts.check('500 16px "Onest Variable"','Резюме'))).toBe(true)
  await page.screenshot({path:'test-results/cv-sections.png',fullPage:true})
  await page.getByRole('button',{name:'Вакансии',exact:true}).click()
  await expect(page.getByRole('button',{name:'Добавить вакансию',exact:true})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Обновить вакансии',exact:true})).toBeDisabled()
  await expect(page.getByText('После подключения HeadHunter здесь появятся вакансии для вашего профиля.')).toBeVisible()
})

test('vacancy search sends selected profile overrides',async({page})=>{
  await register(page,`filters-${Date.now()}@example.com`)
  await page.getByRole('button',{name:'Вакансии',exact:true}).click()
  await page.getByLabel('Фильтр направления').selectOption('qa')
  await page.getByLabel('Фильтр уровня').selectOption('middle')
  await page.getByLabel('Регион',{exact:true}).fill('Алматы')
  await page.getByLabel('Формат работы',{exact:true}).selectOption('hybrid')
  const pending=page.waitForRequest(r=>r.url().endsWith('/vacancies/hh/sync')&&r.method()==='POST')
  await page.getByRole('button',{name:'Обновить вакансии',exact:true}).click()
  const request=await pending
  expect(request.postDataJSON()).toMatchObject({regions:['Алматы'],direction:'qa',level:'middle',work_format:'hybrid'})
  expect(request.postDataJSON()).not.toHaveProperty('area')
})

test('record audio, review transcript before grading',async({page})=>{
  await page.context().grantPermissions(['microphone'])
  await register(page,`voice-${Date.now()}@example.com`)
  const identity=await (await page.request.get('/api/v1/auth/me')).json()
  const sync=await (await page.request.post('/api/v1/vacancies/hh/sync',{
    headers:{'X-CSRF-Token':identity.csrf},data:{text:'Python',area:'40',direction:'python',level:'junior',work_format:'any'}
  })).json()
  await expect.poll(async()=> (await (await page.request.get('/api/v1/jobs/'+sync.job_id)).json()).status).toBe('completed')
  const [vacancy]=await (await page.request.get('/api/v1/records/vacancy')).json()
  await page.reload()
  await page.getByRole('button',{name:'Интервью',exact:true}).click()
  await page.getByLabel('Вакансия',{exact:true}).selectOption(vacancy.id)
  await page.getByLabel('Направление',{exact:true}).selectOption('python')
  await page.getByRole('button',{name:'Начать интервью',exact:true}).click()
  await expect(page.getByText('Вопрос 1 из 5')).toBeVisible()
  await page.getByRole('button',{name:'Записать ответ'}).click()
  await expect(page.getByRole('button',{name:/Остановить · [2-9] с/})).toBeVisible()
  await page.getByRole('button',{name:/Остановить/}).click()
  await expect(page.getByLabel('Ваш ответ',{exact:true})).toHaveValue(/Транзакция фиксирует/)
  await expect(page.getByRole('button',{name:'Оценить ответ',exact:true})).toBeDisabled()
  await page.getByLabel('Я проверил текст ответа').check()
  await page.getByRole('button',{name:'Оценить ответ',exact:true}).click()
  await expect(page.getByText('Вопрос 2 из 5')).toBeVisible()
})

test('administrator reviews extracted question before publishing',async({page})=>{
  await register(page,'owner@example.com')
  await page.getByRole('button',{name:'База знаний',exact:true}).click()
  await page.getByLabel('Ссылка на YouTube').fill('https://www.youtube.com/watch?v=zibAC8HkGFk')
  await page.getByLabel('Направление',{exact:true}).selectOption('python')
  await page.getByRole('button',{name:'Добавить источник',exact:true}).click()
  await page.getByLabel('Загрузить файл источника').setInputFiles({name:'source.srt',mimeType:'text/plain',
    buffer:Buffer.from('1\n00:00:01,000 --> 00:00:20,000\nЧто означает rollback? Кандидат: фиксирует изменения. Интервьюер: нет, отменяет изменения.\n','utf8')})
  await expect(page.getByText('Расшифровка · manual.srt',{exact:false})).toBeVisible()
  await page.getByRole('button',{name:'Извлечь вопросы',exact:true}).click()
  await page.getByRole('button',{name:'Вопросы',exact:true}).click()
  const question=page.getByRole('button',{name:/Что означает rollback в транзакции/})
    await expect(question).toBeVisible()
    await question.click()
    const sourceReview=page.getByRole('region',{name:'Сверка с источником'})
    await expect(sourceReview.getByRole('link',{name:/Открыть видео/})).toHaveAttribute('href',/t=1s/)
    await sourceReview.getByText('Субтитры этого обсуждения',{exact:false}).click()
    await expect(sourceReview.getByText(/Кандидат: фиксирует изменения/)).toBeVisible()
    await page.getByLabel('Начало, секунды').fill('1.25')
    await page.getByLabel('Конец, секунды').fill('15.75')
    await page.getByRole('button',{name:'Сохранить черновик',exact:true}).click()
    await expect(page.getByRole('status').filter({hasText:'Черновик сохранён'})).toBeVisible()
    await page.getByRole('button',{name:'Проверено · опубликовать',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Для публикации дополните контекст')
  await page.getByLabel('Проверенный эталон').fill('Rollback отменяет все изменения текущей транзакции; commit фиксирует изменения.')
  await page.getByLabel('Критерии оценки',{exact:false}).fill('Различает rollback и commit\nОбъясняет отмену всех изменений\nПриводит пример')
  await page.getByLabel('TEST FIXTURE — Transactions',{exact:false}).check()
  await page.getByLabel('Контекст неполный или роли неясны',{exact:false}).uncheck()
  await page.getByLabel('Роли говорящих и основания').fill('Вопрос задаёт интервьюер, кандидат отвечает, интервьюер исправляет ответ.')
  await page.getByRole('button',{name:'Проверено · опубликовать',exact:true}).click()
  await expect(question).toContainText('Опубликовано')
  await expect(page.getByRole('link',{name:'Исходное обсуждение 1'})).toHaveAttribute('href',/t=1s/)
})
