import { test, expect } from '@playwright/test'

test('self study without CV, explicit save, guard, tasks, mobile and login',async({page})=>{
  const email=`study-${Date.now()}@example.com`
  await page.goto('/')
  await page.getByRole('button',{name:'Нет аккаунта? Зарегистрироваться'}).click()
  await page.getByLabel('Email',{exact:true}).fill(email)
  await page.getByLabel('Пароль',{exact:true}).fill('browser-test-pass-42')
  await page.getByRole('button',{name:'Создать аккаунт'}).click()
  await page.getByRole('button',{name:'Вопросы',exact:true}).click()
  await page.getByLabel('Направление',{exact:true}).selectOption('python')
  await page.getByLabel('Поиск',{exact:true}).fill('Вопрос 1:')
  await page.getByRole('button',{name:/Вопрос 1: как работает транзакция/}).click()
  await page.getByLabel('Ваш ответ',{exact:true}).fill('Мой сохранённый ответ')
  await page.getByRole('button',{name:'Раскрыть проверенный эталон'}).click()
  await expect(page.getByRole('heading',{name:'Проверенный эталон',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Знаю',exact:true}).click()
  await page.getByRole('button',{name:'Практические задания',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button',{name:'Остаться',exact:true}).click()
  await expect(page.getByLabel('Ваш ответ',{exact:true})).toHaveValue('Мой сохранённый ответ')
  await page.getByRole('button',{name:'Практические задания',exact:true}).click()
  await page.getByRole('button',{name:'Сохранить',exact:true}).click()
  await page.getByLabel('Направление',{exact:true}).selectOption('python')
  await page.getByRole('button',{name:/Вопрос 1: как работает транзакция/}).click()
  await expect(page.getByLabel('Ваше решение — текст или код')).toHaveValue('')
  await page.getByRole('button',{name:'Раскрыть решение и разбор'}).click()
  await expect(page.getByText('Отдельное проверенное решение пока не опубликовано.')).toBeVisible()
  await expect(page.getByRole('heading',{name:'Теоретический разбор'})).toBeVisible()
  await page.getByLabel('Ваше решение — текст или код').fill('discard this')
  await page.getByRole('button',{name:'Назад к списку'}).click()
  await page.getByRole('button',{name:'Не сохранять',exact:true}).click()
  await page.getByRole('button',{name:'Вопросы',exact:true}).click()
  await expect(page.getByLabel('Ваш ответ',{exact:true})).toHaveValue('Мой сохранённый ответ')
  await page.getByRole('button',{name:'Назад к списку'}).click()
  await expect(page.getByLabel('Поиск',{exact:true})).toHaveValue('Вопрос 1:')
  await page.screenshot({path:'test-results/study-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await page.getByRole('button',{name:/Вопрос 1: как работает транзакция/}).click()
  await expect(page.getByRole('button',{name:'Раскрыть проверенный эталон'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await page.screenshot({path:'test-results/study-mobile.png',fullPage:true})
  await page.getByRole('button',{name:'Назад к списку'}).click()
  await page.getByLabel('Поиск',{exact:true}).fill('')
  const last=page.getByRole('button',{name:/Вопрос 5: как работает транзакция/})
  await last.scrollIntoViewIfNeeded()
  const position=await page.evaluate(()=>window.scrollY)
  await last.click()
  await page.getByRole('button',{name:'Назад к списку'}).click()
  await expect.poll(async()=>Math.abs(await page.evaluate(()=>window.scrollY)-position)).toBeLessThan(4)
  await page.getByRole('button',{name:'Выйти',exact:true}).click()
  await page.getByLabel('Email',{exact:true}).fill(email)
  await page.getByLabel('Пароль',{exact:true}).fill('browser-test-pass-42')
  await page.getByRole('button',{name:'Войти',exact:true}).click()
  await page.getByRole('button',{name:'Вопросы',exact:true}).click()
  await page.getByLabel('Направление',{exact:true}).selectOption('python')
  await page.getByRole('button',{name:/Вопрос 1: как работает транзакция/}).click()
  await expect(page.getByLabel('Ваш ответ',{exact:true})).toHaveValue('Мой сохранённый ответ')
  await expect(page.getByRole('button',{name:'Знаю',exact:true})).toHaveAttribute('aria-pressed','true')
})
