import { ProfileData, User, AuthResult, CVFacts, ParseDraft, Fragment, DocumentBlock, Turn, Job, Connections, Availability, Statistics, UsageSummary, UsageOperation, QuestionInput, SourceRef, Segment, Workspace, Direction, Level, Language, Evaluation } from './models'
import React, { useEffect, useRef, useState } from 'react'
import { ArrowUpRight, ArrowRight, BriefcaseBusiness, Check, ChevronRight, FileText, GraduationCap, LayoutDashboard, LogOut, Mic, Plus, Search, Settings, ShieldCheck, Sparkles, TrendingUp, Upload, X, Play, Square, Bookmark, ExternalLink, LoaderCircle, CheckCircle2, Clock3, Headphones } from 'lucide-react'
import { api, setCSRF, setRequestScope, fileBody, Entry, directionName, statusName } from './api'
import { Field, Badge, Empty, Filters, VacancySelect } from './ui'
import { Action, emptyFacts, defaultProfile } from './shared'
export function CVPage({rows,act,aiConnected}:{rows:Entry<'cv'>[];act:Action;aiConnected:boolean}) {
  const [text,setText]=useState(''),[active,setActive]=useState(''),[facts,setFacts]=useState<CVFacts>(emptyFacts)
  const row=rows.find(r=>r.id===active)||rows[0]
  useEffect(()=>{setFacts(row?.data.facts||emptyFacts)},[row?.id,JSON.stringify(row?.data.facts)])
  return <div className="two-col"><section className="panel"><h2>Добавьте резюме</h2><p className="muted">PDF с текстовым слоем или DOCX, до 10 МБ.</p><label className="upload-zone"><Upload size={28}/><strong>Выбрать файл резюме</strong><span>или вставьте текст ниже</span><input aria-label="Загрузить резюме" type="file" accept=".pdf,.docx" onChange={e=>{const file=e.target.files?.[0];if(file)act(async()=>{const r=await api('/cv/upload','POST',fileBody(file));setActive(r.id);return r})}}/></label>
    <form onSubmit={e=>{e.preventDefault();act(async()=>{const r=await api('/cv/text','POST',{text});setActive(r.id);setText('');return r},'Резюме добавлено')}}><Field label="Текст резюме"><textarea rows={7} minLength={40} maxLength={60000} value={text} onChange={e=>setText(e.target.value)} placeholder="Опыт, навыки, проекты и образование…" required/></Field><button className="btn secondary"><Plus size={16}/>Добавить текст</button></form>
    {row&&<details className="space-top"><summary>Повторно распределить исходный текст</summary><p className="muted">Поля будут заполнены заново по заголовкам CV. Сохранённые факты останутся в истории; новый результат нужно подтвердить.</p><button className="btn secondary" onClick={()=>act(()=>api(`/cv/${row.id}/sections`,'POST'),'Разделы заполнены заново. Проверьте результат.')}>Распределить по разделам</button></details>}
    <h3 className="space-top">Ваши версии</h3>{rows.map(r=><button key={r.id} className={'list-item '+(r.id===row?.id?'selected':'')} onClick={()=>setActive(r.id)}><FileText size={18}/><span>{r.data.filename}<small>{new Date(r.created_at).toLocaleDateString('ru-RU')}</small></span><Badge status={r.status}/></button>)}</section>
    <section className="panel">{row?<><div className="section-heading"><h2>Проверьте профиль</h2><Badge status={row.status}/></div><p className="muted">Разделы с заголовками распределены автоматически. Проверьте каждый пункт: в документы попадут только подтверждённые факты.</p><button className="btn secondary" disabled={!aiConnected} onClick={()=>act(()=>api(`/cv/${row.id}/parse`,'POST'))}><Sparkles size={16}/>Извлечь факты с ИИ</button>{!aiConnected&&<p className="muted">ИИ-разбор пока недоступен. Вы можете проверить и заполнить поля самостоятельно.</p>}{row.data.parse_drafts?.map((draft)=><div key={draft.job_id} className="space-top"><p>Черновик ИИ · {new Date(draft.created_at).toLocaleString('ru-RU')} · исходная версия {draft.base_version}</p>{draft.warning&&<p>{draft.warning}</p>}<button className="btn secondary" onClick={()=>setFacts(draft.facts)}>Проверить этот черновик в редакторе</button></div>)}{row.data.unassigned_text&&<details className="space-top" open><summary>Текст без определённого раздела</summary><p className="muted">Перенесите нужные сведения в подходящие поля. Контакты не нужны для подбора.</p><pre>{row.data.unassigned_text}</pre></details>}
    <form className="space-top" onSubmit={e=>{e.preventDefault();act(()=>api(`/cv/${row.id}/confirm`,'PUT',facts,String(row.data.version||1)),'Профиль резюме подтверждён')}}><Field label="Кратко о себе"><textarea rows={4} value={facts.summary||''} onChange={e=>setFacts({...facts,summary:e.target.value})}/></Field>{[['skills','Навыки'],['experience','Опыт работы'],['education','Образование'],['projects','Проекты'],['languages','Языки']].map(([key,label])=><Field key={key} label={label}><textarea rows={key==='experience'?4:2} value={(facts[key as keyof Omit<CVFacts,'summary'>]||[]).join('\n')} onChange={e=>setFacts({...facts,[key]:e.target.value.split('\n')})}/></Field>)}<button className="btn primary"><Check size={17}/>Подтвердить факты</button></form><details className="space-top"><summary>Исходный текст</summary><pre>{row.data.text}</pre></details><p className="muted">Сохранённых изменений: {row.data.versions?.length||0}</p></>:<Empty title="Резюме ещё нет" text="Добавьте файл или текст, чтобы собрать свой профиль."/>}</section></div>
}

