import { ProfileData, User, AuthResult, CVFacts, ParseDraft, Fragment, DocumentBlock, Turn, Job, Connections, Availability, Statistics, UsageSummary, UsageOperation, QuestionInput, SourceRef, Segment, Workspace, Direction, Level, Language, Evaluation } from './models'
import React, { useEffect, useRef, useState } from 'react'
import { ArrowUpRight, ArrowRight, BriefcaseBusiness, Check, ChevronRight, FileText, GraduationCap, LayoutDashboard, LogOut, Mic, Plus, Search, Settings, ShieldCheck, Sparkles, TrendingUp, Upload, X, Play, Square, Bookmark, ExternalLink, LoaderCircle, CheckCircle2, Clock3, Headphones } from 'lucide-react'
import { api, setCSRF, setRequestScope, fileBody, Entry, directionName, statusName } from './api'
import { Field, Badge, Empty, Filters, VacancySelect } from './ui'
import { Action, emptyFacts, defaultProfile } from './shared'
export function Documents({rows,vacancies,cv,selected,act}:{rows:Entry<'document'>[];vacancies:Entry<'vacancy'>[];cv?:Entry<'cv'>;selected:string;act:Action}) {
  const [vacancy,setVacancy]=useState(selected),[kind,setKind]=useState('cover_letter'),[language,setLanguage]=useState('ru'),[active,setActive]=useState(''),[text,setText]=useState('')
  const [checked,setChecked]=useState(false),[acceptClaims,setAcceptClaims]=useState(false)
  const row=rows.find(r=>r.id===active)||rows[0]
  useEffect(()=>{setText(row?.data.text||'');setChecked(false);setAcceptClaims(false)},[row?.id,row?.updated_at])
  return <div className="two-col"><section className="panel"><h2>Подготовить документ</h2><p className="muted">Переставим акценты на основе подтверждённого опыта. Вы проверите результат перед сохранением.</p><form onSubmit={e=>{e.preventDefault();act(()=>api('/documents','POST',{vacancy_id:vacancy,cv_id:cv?.id,kind,language}))}}><VacancySelect rows={vacancies} value={vacancy} set={setVacancy}/><Field label="Тип документа"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="cover_letter">Сопроводительное письмо</option><option value="adapted_cv">Адаптированное резюме</option></select></Field><Field label="Язык оформления"><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="ru">Русский</option><option value="en">English</option></select></Field><button className="btn primary" disabled={!cv}><Sparkles size={17}/>Подготовить черновик</button>{!cv&&<p className="muted">Сначала подтвердите факты в резюме.</p>}</form><h3 className="space-top">Ваши документы</h3>{rows.map(r=><button className={'list-item '+(r.id===row?.id?'selected':'')} key={r.id} onClick={()=>setActive(r.id)}><FileText size={17}/><span>{r.data.title}</span><Badge status={r.status}/></button>)}</section>
  <section className="panel">{row?<><div className="section-heading"><h2>{row.data.title}</h2><Badge status={row.status}/></div>{row.data.requires_confirmation&&<div className="fragment-review"><h3>Сверка перевода с фактами</h3>{row.data.fragments.map((f,i:number)=><div className="fragment-pair" key={i}><div><strong>Исходный факт</strong><p className="pre-wrap">{f.source_text}</p></div><div><strong>Предложенный фрагмент {i+1}</strong><p className="pre-wrap">{f.proposed_text||f.text}</p>{f.issues.map((issue:string,j:number)=><p className="error-text" key={j}>{issue}</p>)}</div></div>)}</div>}<Field label="Редактор документа"><textarea rows={17} value={text} onChange={e=>{setText(e.target.value);setChecked(false)}}/></Field><label className="checkbox"><input type="checkbox" checked={acceptClaims} onChange={e=>setAcceptClaims(e.target.checked)}/>Принимаю свои изменения: «Добавлено пользователем; не проверено по CV»</label>{row.data.blocks?.some((b)=>b.origin==='user')&&<p className="muted">Документ содержит блоки «Добавлено пользователем; не проверено по CV».</p>}<details open><summary>Предложенные изменения</summary><ul>{row.data.changes.map((s:string,i:number)=><li key={i}>{s}</li>)}</ul></details><details><summary>Подтверждённые исходные факты</summary><ul>{Object.values(row.data.original_facts||{}).map((s,i)=><li key={i}>{s}</li>)}</ul></details><p className="muted">{row.data.language_note}</p><div>{row.data.requires_confirmation&&<label className="checkbox"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Я проверил и подтверждаю итоговый текст</label>}</div><div className="button-row"><button className="btn primary" disabled={row.data.requires_confirmation&&!checked} onClick={()=>act(()=>api('/documents/'+row.id,'PUT',{text,confirmed:checked,accept_user_claims:acceptClaims},row.updated_at),'Документ сохранён')}>Сохранить</button><button className="btn secondary" onClick={()=>act(async()=>{await navigator.clipboard.writeText(text)},'Текст скопирован')}>Копировать</button>{(!row.data.requires_confirmation||row.data.approved)&&<a className="btn secondary" href={`/api/v1/documents/${row.id}/export`}>Скачать DOCX</a>}</div><small className="muted">Экспортируется последняя сохранённая версия. Отклик отправьте на площадке вакансии.</small></>:<Empty title="Документ появится здесь" text="Выберите вакансию и подготовьте первый черновик."/>}</section></div>
}

