import { useAudioRecorder } from './useAudioRecorder'
import { ProfileData, User, AuthResult, CVFacts, ParseDraft, Fragment, DocumentBlock, Turn, Job, Connections, Availability, Statistics, UsageSummary, UsageOperation, QuestionInput, SourceRef, Segment, Workspace, Direction, Level, Language, Evaluation } from './models'
import React, { useEffect, useRef, useState } from 'react'
import { ArrowUpRight, ArrowRight, BriefcaseBusiness, Check, ChevronRight, FileText, GraduationCap, LayoutDashboard, LogOut, Mic, Plus, Search, Settings, ShieldCheck, Sparkles, TrendingUp, Upload, X, Play, Square, Bookmark, ExternalLink, LoaderCircle, CheckCircle2, Clock3, Headphones } from 'lucide-react'
import { api, setCSRF, setRequestScope, fileBody, Entry, directionName, statusName } from './api'
import { Field, Badge, Empty, Filters, VacancySelect } from './ui'
import { Action, emptyFacts, defaultProfile } from './shared'
export function Interviews({rows,vacancies,profile,jobs,act,audioAvailable}:{rows:Entry<'interview'>[];vacancies:Entry<'vacancy'>[];profile:ProfileData;jobs:Job[];act:Action;audioAvailable:boolean}) {
  const [vacancy,setVacancy]=useState(''),[choice,setChoice]=useState<ProfileData>(profile),[active,setActive]=useState(''),[answer,setAnswer]=useState(''),[confirmed,setConfirmed]=useState(false)
  const [availability,setAvailability]=useState<Availability[]>([])
  useEffect(()=>{api('/knowledge/availability').then(setAvailability).catch(()=>setAvailability([]))},[rows.length])
  const available=availability.find(a=>a.direction===choice.direction&&a.level===choice.level&&a.language===choice.language)
  const [audioJob,setAudioJob]=useState('')
  const row=rows.find(r=>r.id===active)||rows[0], index=row?.data.turns.findIndex((t)=>!t.evaluation)??0
  const turn=index>=0?row?.data.turns[index]:null
  const {recording,seconds,error:audioError,setError:setAudioError,start,stop}=useAudioRecorder(row?.id,index,act)
  useEffect(()=>{setAnswer(index>=0?turn?.answer||turn?.transcript||'':'');setConfirmed(false);setAudioJob(turn?.audio_job_id||'')},[row?.id,index])
  const appliedAudio=useRef('')
  useEffect(()=>{const job=jobs.find(j=>j.id===(turn?.audio_job_id||audioJob));
    if(job?.status==='completed'&&job.result.interview_id===row?.id&&job.result.index===index&&appliedAudio.current!==job.id&&!turn?.submitted) {
      setAnswer(job.result.text||'');setConfirmed(false);setAudioJob('');appliedAudio.current=job.id
    }
    if(job&&['failed','paused','needs_review'].includes(job.status)){setAudioError(job.error||'Распознавание остановлено');setAudioJob('')}
  },[jobs,audioJob,row?.id,index,turn?.audio_job_id])
  const attempt=jobs.find(j=>j.kind==='evaluate'&&j.context?.interview_id===row?.id&&j.context?.index===index)
  const frozen=!!attempt&&(['running','needs_review'].includes(attempt.status)||attempt.sent)
  const pending=!!attempt&&['queued','running'].includes(attempt.status)
  return <><form className="panel space-bottom" onSubmit={e=>{e.preventDefault();act(async()=>{const r=await api('/interviews','POST',{vacancy_id:vacancy,direction:choice.direction,level:choice.level,language:choice.language});setActive(r.id);return r})}}><div className="section-heading"><div><h2>Пять вопросов. Один шаг вперёд.</h2><p className="muted">Отвечайте текстом или голосом. К незавершённой сессии можно вернуться.</p></div><span className="tag">В ВАШЕМ ТЕМПЕ</span></div><VacancySelect rows={vacancies} value={vacancy} set={setVacancy}/><Filters value={choice} onChange={setChoice}/><p className="muted">{available?`Опубликовано ${available.questions} вопросов.${available.missing?` Для интервью не хватает ещё ${available.missing}.`:" Можно начинать."}`:"Проверяем наличие вопросов…"}</p><button className="btn primary" disabled={!available?.interview_ready}><Play size={17}/>Начать интервью</button></form>
  <div className="two-col interview-grid"><aside className="panel"><h2>Ваши сессии</h2>{rows.length?rows.map(r=><button key={r.id} className={'list-item '+(row?.id===r.id?'selected':'')} onClick={()=>{stop();setActive(r.id)}}><Headphones size={18}/><span>{directionName[r.data.direction]} · {r.data.level}<small>{new Date(r.created_at).toLocaleString('ru-RU')}</small></span><Badge status={r.status}/></button>):<p className="muted">Первая сессия появится здесь.</p>}</aside>
  <section className="panel">{row?<><div className="section-heading"><span className="eyebrow">{directionName[row.data.direction]} / {row.data.language.toUpperCase()}</span><Badge status={row.status}/></div><div className="question-progress">{row.data.turns.map((t,i:number)=><span key={i} className={t.evaluation?'complete':i===index?'current':''}/>)}</div>{turn?<><span className="muted">Вопрос {index+1} из 5 · {turn.question.topic}</span><h2 className="question-title">{turn.question.question}</h2>{turn.fallback&&<p className="muted">Общий вопрос для практики: совпадение с требованиями вакансии не найдено.</p>}{turn.question.task&&<pre>{turn.question.task}</pre>}<Field label="Ваш ответ"><textarea rows={8} maxLength={16000} disabled={frozen} value={answer} onChange={e=>{setAnswer(e.target.value);setConfirmed(false)}} placeholder="Объясните решение и ход рассуждений. Здесь можно вставить код."/></Field><div className="button-row"><button className={'btn '+(recording?'danger':'secondary')} onClick={recording?stop:start} disabled={jobs.some(j=>j.id===(turn?.audio_job_id||audioJob)&&['queued','running','needs_review'].includes(j.status))||!audioAvailable}>{recording?<Square size={17}/>:<Mic size={17}/>} {recording?`Остановить · ${seconds} с`:'Записать ответ'}</button><small className="muted">{audioAvailable?'До 3 минут · оценка без учёта акцента':'Голос не подключён — отвечайте текстом.'}</small></div>{audioError&&<p className="error-text">{audioError}</p>}{audioJob&&<p className="muted">Распознавание: {statusName[jobs.find(j=>j.id===audioJob)?.status||'queued']||'В очереди'}. Проверьте раздел «Операции», если операция приостановлена.</p>}{attempt&&['paused','failed','needs_review'].includes(attempt.status)&&<p className="muted">{attempt.error} {frozen?'Попытка сохранена. Продолжение или сверка доступны в разделе «Операции».':'Можно исправить ответ и отправить снова.'}</p>}<label className="checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Я проверил текст ответа и подтверждаю его для оценки</label><button className="btn primary" disabled={!confirmed||!answer.trim()||pending||recording||frozen} onClick={()=>act(()=>api(`/interviews/${row.id}/answers/${index}`,'POST',{text:answer,confirmed:true}))}>Оценить ответ<ArrowRight size={17}/></button></>:<div className="completion"><CheckCircle2 size={38}/><h2>Интервью завершено</h2><p>Вы сделали ещё один шаг. Посмотрите разбор и вернитесь к сложным темам.</p></div>}
  {row.data.turns.map((t,i:number)=>t.evaluation&&<details className="feedback" open={i===index-1||index===-1} key={i}><summary>Разбор {i+1}: {t.question.topic} <span>{t.evaluation.reliable?`${t.evaluation.correctness} / 4`:'Без оценки'}</span></summary><p><strong>{t.question.question}</strong></p><p className="pre-wrap">Ваш ответ: {t.answer}</p><div className="score-row">{[['correctness','Правильность'],['completeness','Полнота'],['reasoning','Обоснование']].map(([k,label])=><span key={k}>{label}<strong>{t.evaluation![k as keyof Pick<Evaluation,'correctness'|'completeness'|'reasoning'>]??'—'} <small>/ 4</small></strong></span>)}</div><p>{t.evaluation.feedback}</p>{t.evaluation.errors.length>0&&<><h4>Ошибки</h4><ul>{t.evaluation.errors.map((s:string,i:number)=><li key={i}>{s}</li>)}</ul></>}{t.evaluation.missing_points.length>0&&<><h4>Что дополнить</h4><ul>{t.evaluation.missing_points.map((s:string,i:number)=><li key={i}>{s}</li>)}</ul></>}{t.evaluation.improved_answer&&<><h4>Пример более полного ответа</h4><p className="pre-wrap">{t.evaluation.improved_answer}</p></>}{t.materials.map((m,i:number)=><a key={m.id} className="material-link" href={m.url} target="_blank" rel="noreferrer">Материал {i+1}<ExternalLink size={14}/></a>)}<small className="muted">Критерии: версия {t.rubric_version}</small></details>)}</>:<Empty icon={Headphones} title="Можно спокойно потренироваться" text="Выберите вакансию и начните сессию из пяти проверенных вопросов."/>}</section></div></>
}

