export type Direction = 'frontend' | 'python' | 'qa'
export type Level = 'junior' | 'middle'
export type Language = 'ru' | 'en'
export type ProfileData = {direction:Direction; level:Level; language:Language; regions:string[]; work_format:'remote'|'office'|'hybrid'|'any'}
export type User = {id:string;email:string;role:'admin'|'user';profile:ProfileData}
export type AuthResult = {user:User;csrf:string}
export type CVFacts = {summary:string;skills:string[];experience:string[];education:string[];projects:string[];languages:string[]}
export type ParseDraft = {job_id:string;facts:CVFacts;base_version:number;warning:string;created_at:string}
export type CVData = {filename:string;text:string;facts:CVFacts;version?:number;unassigned_text?:string;versions?:unknown[];parse_drafts?:ParseDraft[]}
export type Match = {score:number;reasons:string[];matching_skills:string[];missing_skills:string[];cv_id:string;cv_version:number;facts_hash:string;vacancy_hash:string}
export type VacancyData = {title:string;company:string;description:string;url?:string;direction:Direction;level:Level;hh_experience?:string;region:string;region_parents?:string[];work_format:ProfileData['work_format'];work_formats?:string[];favorite:boolean;match?:Match;match_stale?:boolean}
export type Fragment = {text:string;proposed_text:string;source_text:string;fact_ids:string[];issues:string[]}
export type DocumentBlock = {text:string;origin:'cv'|'model'|'user'|'template';fact_ids:string[];verified_by_cv:boolean}
export type DocumentData = {title:string;text:string;fragments:Fragment[];blocks?:DocumentBlock[];requires_confirmation:boolean;approved:boolean;changes:string[];original_facts:Record<string,string>;language_note:string}
export type MaterialRef = {id:string;url:string;text?:string;version?:number}
export type PlanDay = {day:number;title:string;question_id:string;question:string;repeat:boolean;fallback?:boolean;repeat_reason?:string;example:string;task:string;materials:MaterialRef[];done:boolean}
export type PlanData = {days:PlanDay[];review:string;shortage:number}
export type SourceRef = {source_id:string;video_id:string;start:number;end:number}
export type Segment = {text:string;start:number;end:number;speaker?:string}
export type SourceData = {url:string;video_id:string;direction:Direction;level:Level;language:Language;transcript?:{method:string;segments:Segment[]}}
export type QuestionInput = {question:string;followups:string[];candidate_answer:string;interviewer_notes:string;task:string;task_solution?:string;topic:string;direction:Direction;level:Level;language:Language;start:number;end:number;roles:string;needs_context:boolean;reference_answer:string;rubric:string[];material_ids:string[];translation_of:string|null}
export type QuestionData = QuestionInput & {version:number;sources:SourceRef[];review_note?:string;review_scope?:string}
export type MaterialData = {title:string;text:string;url:string;direction:Direction;level:Level;language:Language}
export type Evaluation = {reliable:boolean;correctness:number|null;completeness:number|null;reasoning:number|null;feedback:string;errors:string[];missing_points:string[];improved_answer:string}
export type Turn = {question_id:string;fallback?:boolean;question:QuestionData;rubric_version:number;materials:MaterialRef[];answer:string;evaluation:Evaluation|null;submitted?:boolean;audio_job_id?:string;transcript?:string}
export type InterviewData = {direction:Direction;level:Level;language:Language;turns:Turn[]}
export type DataByKind = {cv:CVData;vacancy:VacancyData;document:DocumentData;plan:PlanData;interview:InterviewData;question:QuestionData;material:MaterialData;source:SourceData}
export type Entry<K extends keyof DataByKind=keyof DataByKind> = {[P in K]:{id:string;kind:P;status:string;data:DataByKind[P];created_at:string;updated_at:string}}[K]
export type Workspace = {[K in 'cv'|'vacancy'|'document'|'plan'|'interview']:Entry<K>[]}
export type JobStatus = 'queued'|'running'|'paused'|'completed'|'failed'|'needs_review'
export type Job = {id:string;kind:string;status:JobStatus;error:string|null;created_at:string;attempts:number;completed_steps:string[];context:{interview_id?:string;index?:number};sent:boolean;result:{text?:string;interview_id?:string;index?:number;record_id?:string}}
export type Connections = {openai?:boolean;text_ai?:boolean;text_provider?:string;audio?:boolean;hh?:boolean;gemini_free_tier?:boolean;hh_last?:{created_at:string;status:JobStatus;error?:string}}
export type Availability = {direction:Direction;level:Level;language:Language;questions:number;missing:number;interview_ready:boolean}
export type Statistics = {timeline:{id:string;date:string;score:number;answers:number}[];topics:{topic:string;score:number;answers:number}[];errors:{error:string;count:number}[]}
export type UsageOperation = {key:string;model:string;state:string;actual:number|null;reserved:number;details?:{method?:string;input_tokens?:number;output_tokens?:number;duration_seconds?:number}}
export type UsageSummary = {month?:string;charged_and_reserved?:number;limit?:number;completed?:number;open_reservations?:number;remaining?:number;audio_estimates?:number;video_hours?:number;operations?:UsageOperation[]}
