import { ProfileData, User, AuthResult, CVFacts, ParseDraft, Fragment, DocumentBlock, Turn, Job, Connections, Availability, Statistics, UsageSummary, UsageOperation, QuestionInput, SourceRef, Segment, Workspace, Direction, Level, Language, Evaluation } from './models'
import React, { useEffect, useRef, useState } from 'react'
import { ArrowUpRight, ArrowRight, BriefcaseBusiness, Check, ChevronRight, FileText, GraduationCap, LayoutDashboard, LogOut, Mic, Plus, Search, Settings, ShieldCheck, Sparkles, TrendingUp, Upload, X, Play, Square, Bookmark, ExternalLink, LoaderCircle, CheckCircle2, Clock3, Headphones } from 'lucide-react'
import { api, setCSRF, setRequestScope, fileBody, Entry, directionName, statusName } from './api'
import { Field, Badge, Empty, Filters, VacancySelect } from './ui'
import { Action, emptyFacts, defaultProfile } from './shared'
export function Plans({rows,vacancies,cv,act}:{rows:Entry<'plan'>[];vacancies:Entry<'vacancy'>[];cv?:Entry<'cv'>;act:Action}) {
  const [vacancy,setVacancy]=useState(''),[active,setActive]=useState('')
  const row=rows.find(r=>r.id===active)||rows[0]
  return <><form className="panel compact-form" onSubmit={e=>{e.preventDefault();act(()=>api('/plans','POST',{vacancy_id:vacancy,cv_id:cv?.id}))}}><div><h2>Семь дней до большей уверенности</h2><p className="muted">Темы, примеры и практика из проверенной базы знаний.</p></div><VacancySelect rows={vacancies} value={vacancy} set={setVacancy}/><button className="btn primary" disabled={!cv}><GraduationCap size={17}/>Составить план</button></form>{rows.length>1&&<Field label="Сохранённый план"><select value={row?.id} onChange={e=>setActive(e.target.value)}>{rows.map((r,i)=><option value={r.id} key={r.id}>План {rows.length-i} · {new Date(r.created_at).toLocaleDateString('ru-RU')}</option>)}</select></Field>}
  {row?<><div className="section-heading space-top"><h2>Ваш маршрут на неделю</h2><span className="tag">{row.data.days.filter((d)=>d.done).length} / 7 дней</span></div><p className="muted">{row.data.review}{row.data.shortage>0&&` Для семи разных дней не хватает ${row.data.shortage} вопросов.`}</p><div className="days">{row.data.days.map((d)=><section className={'panel day '+(d.done?'day-done':'')} key={d.day}><div className="day-top"><span className="eyebrow">ДЕНЬ {String(d.day).padStart(2,'0')}</span><button className={'check-button '+(d.done?'checked':'')} aria-label={`Отметить день ${d.day}`} onClick={()=>act(()=>api(`/plans/${row.id}/days/${d.day}`,'POST'))}>{d.done&&<Check size={17}/>}</button></div><h2>{d.title}</h2>{d.repeat&&<span className="tag">{d.repeat_reason||"Повторение"}</span>}<p>{d.question}</p>{d.fallback&&<p className="muted">Общий вопрос для практики: совпадение с требованиями вакансии не найдено.</p>}<details><summary>Пример ответа</summary><p className="pre-wrap">{d.example}</p></details><div className="practice"><strong>Практика</strong><p>{d.task}</p></div>{d.materials.map((m,i:number)=><a className="material-link" key={m.id} href={m.url} target="_blank" rel="noreferrer">Материал {i+1}<ArrowUpRight size={14}/></a>)}</section>)}</div></>:<Empty icon={GraduationCap} title="Подготовка начинается с плана" text="Выберите вакансию. Для плана нужны опубликованные вопросы вашего направления, уровня и языка."/>}</>
}

