import { ProfileData, User, AuthResult, CVFacts, ParseDraft, Fragment, DocumentBlock, Turn, Job, Connections, Availability, Statistics, UsageSummary, UsageOperation, QuestionInput, SourceRef, Segment, Workspace, Direction, Level, Language, Evaluation } from './models'
import React, { useEffect, useRef, useState } from 'react'
import { ArrowUpRight, ArrowRight, BriefcaseBusiness, Check, ChevronRight, FileText, GraduationCap, LayoutDashboard, LogOut, Mic, Plus, Search, Settings, ShieldCheck, Sparkles, TrendingUp, Upload, X, Play, Square, Bookmark, ExternalLink, LoaderCircle, CheckCircle2, Clock3, Headphones } from 'lucide-react'
import { api, setCSRF, setRequestScope, fileBody, Entry, directionName, statusName } from './api'
import { Field, Badge, Empty, Filters, VacancySelect } from './ui'
import { Action, emptyFacts, defaultProfile } from './shared'
export function Profile({user,act,save}:{user:User;act:Action;save:(u:User|null)=>void}) {
  const [profile,setProfile]=useState<ProfileData>({...defaultProfile,...user.profile}),[deleting,setDeleting]=useState(false)
  return <div className="two-col"><form className="panel" onSubmit={e=>{e.preventDefault();act(async()=>{const r=await api('/profile','PUT',profile);save(r);return r},'Профиль сохранён')}}><h2>Куда вы хотите двигаться?</h2><Filters value={profile} onChange={setProfile}/><Field label="Желаемые регионы, через запятую"><input value={profile.regions.join(', ')} onChange={e=>setProfile({...profile,regions:e.target.value.split(',').map(s=>s.trim())})}/></Field><Field label="Формат работы"><select value={profile.work_format} onChange={e=>setProfile({...profile,work_format:e.target.value as ProfileData['work_format']})}><option value="any">Любой</option><option value="remote">Удалённо</option><option value="office">Офис</option><option value="hybrid">Гибрид</option></select></Field><button className="btn primary">Сохранить профиль</button></form><section className="panel"><h2>Аккаунт</h2><p>{user.email}</p><p className="muted">Роль: {user.role==='admin'?'Администратор':'Пользователь'}</p><hr/><h3>Удаление данных</h3><p className="muted">Будут удалены аккаунт, резюме, личные файлы, документы и история интервью. Опубликованная общая база знаний и обезличенный учёт расходов сохраняются.</p>{deleting?<div><p>Удалить аккаунт без возможности восстановления?</p><div className="button-row"><button className="btn danger" onClick={()=>act(async()=>{await api('/account','DELETE');save(null)})}>Да, удалить мои данные</button><button className="btn secondary" onClick={()=>setDeleting(false)}>Отмена</button></div></div>:<button className="text-button error-text" onClick={()=>setDeleting(true)}>Удалить аккаунт</button>}</section></div>
}

