import { ProfileData, User, AuthResult, CVFacts, ParseDraft, Fragment, DocumentBlock, Turn, Job, Connections, Availability, Statistics, UsageSummary, UsageOperation, QuestionInput, SourceRef, Segment, Workspace, Direction, Level, Language, Evaluation } from './models'
import React, { useEffect, useRef, useState } from 'react'
import { ArrowUpRight, ArrowRight, BriefcaseBusiness, Check, ChevronRight, FileText, GraduationCap, LayoutDashboard, LogOut, Mic, Plus, Search, Settings, ShieldCheck, Sparkles, TrendingUp, Upload, X, Play, Square, Bookmark, ExternalLink, LoaderCircle, CheckCircle2, Clock3, Headphones } from 'lucide-react'
import { api, setCSRF, setRequestScope, fileBody, Entry, directionName, statusName } from './api'
import { Field, Badge, Empty, Filters, VacancySelect } from './ui'
import { Action, emptyFacts, defaultProfile } from './shared'
export function Stats({profile,version}:{profile:ProfileData;version:number}) {
  const [filter,setFilter]=useState(profile),[stats,setStats]=useState<Statistics>({timeline:[],topics:[],errors:[]}),[error,setError]=useState('')
  useEffect(()=>{let current=true;setError('');setStats({timeline:[],topics:[],errors:[]});api(`/stats?direction=${filter.direction}&level=${filter.level}&language=${filter.language}`).then(result=>{if(current)setStats(result)}).catch(e=>{if(current)setError(e.message)});return()=>{current=false}},[filter.direction,filter.level,filter.language,version])
  return <><div className="panel"><Filters value={filter} onChange={setFilter}/><p className="muted">Сравниваются только ответы одного направления, уровня и языка. Недостоверные оценки исключены.</p></div>{error&&<p role="alert">{error}</p>}{stats.timeline.length?<div className="two-col space-top"><section className="panel"><h2>Динамика оценок</h2><div className="chart" role="img" aria-label="Динамика среднего балла интервью от 0 до 4">{stats.timeline.map((s,i:number)=><div className="chart-col" key={s.id}><strong>{s.score}</strong><div style={{height:`${s.score/4*160+3}px`}}/><small>{i+1}</small></div>)}</div><p className="muted">Средний балл по трём критериям. Шкала 0–4.</p>{stats.timeline.map((s)=><div className="stat-line" key={s.id}><span>{new Date(s.date).toLocaleDateString('ru-RU')} · {s.answers} ответов</span><strong>{s.score} / 4</strong></div>)}</section><section className="panel"><h2>Темы для роста</h2>{[...stats.topics].sort((a,b)=>a.score-b.score).map((t)=><div className="topic-stat" key={t.topic}><div><span>{t.topic}</span><strong>{t.score} / 4</strong></div><progress max={4} value={t.score}/></div>)}<h3 className="space-top">Повторяющиеся ошибки</h3>{stats.errors.filter((e)=>e.count>1).map((e)=><p key={e.error}>{e.error} <span className="tag">{e.count} раза</span></p>)}{!stats.errors.some((e)=>e.count>1)&&<p className="muted">Повторяющихся ошибок пока нет.</p>}</section></div>:<Empty icon={TrendingUp} title="Прогресс станет виден с практикой" text="После первых оценённых ответов здесь появятся динамика и темы для повторения."/>}</>
}
